services:
  api:
    build:
      context: .
      dockerfile: BlogApi/Dockerfile
      target: ${TARGET:-development}
    ports:
      - "5077:5077"
      - "5078:5078"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:5077;https://+:5078
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}
    volumes:
      - .:/src
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - DB_HOST=blog-api-db-1
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
