services:
  api:
    build:
      context: .
      dockerfile: BlogApi/Dockerfile
      target: ${TARGET:-development}
    ports:
      - "5077:5077"
      - "5078:5078"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # This is important to override the localhost binding in your Program.cs
      - ASPNETCORE_URLS=http://+:5077;https://+:5078
    volumes:
      - .:/src
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: