name: Deploy Blog API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        # Install sshpass to use password authentication (or set up SSH keys for security)
        sudo apt-get install -y sshpass

        # Copy the publish folder to your VPS
        sshpass -p $VPS_PASSWORD scp -rv ./publish/* $VPS_USER@$VPS_HOST:/var/www/blog-api/publish/

        # SSH into the VPS to restart the application (assuming you're using systemd or a similar service)
        sshpass -p $VPS_PASSWORD ssh -v $VPS_USER@$VPS_HOST << EOF
          cd /var/www/blog-api
          sudo systemctl restart blog-api.service
        EOF